SAS initial data exploration
gclark422/Orange4-Summer pull request #3
Opened 2019-07-09 23:15 UTC by dandexler

2019-07-09 23:18 UTC, gclark422 reviewed
This file needs to be a .sas file

2019-07-09 23:32 UTC, gclark422 approved these changes
Looks good just a few things to keep in mind for next time

2019-07-09 23:32 UTC, gclark422 commented on initial-data-exploration.sas
> +proc import datafile='D:\Data\df_merge.csv' dbms=csv out= summer.df_merge_import replace;
technically this line isnt needed since its the data_step file but it's fine

2019-07-09 23:32 UTC, gclark422 commented on initial-data-exploration.sas
> +data merge_train merge_valid;
This is also in the data_step file

2019-07-10 00:24 UTC, gclark422 requested changes

2019-07-10 00:24 UTC, gclark422 commented on initial-data-exploration.sas
> +  store out=glmameshousing3step;
why outputting to glmhousing?

2019-07-10 00:26 UTC, dandexler commented on initial-data-exploration.sas
> +  store out=glmameshousing3step;
It's the skeleton of the model. It is incomplete and can be modified at a later date, once we decide on the variables we want to include in our model.

2019-07-10 00:29 UTC, gclark422 approved these changes

2019-07-10 00:29 UTC, gclark422 commented
looks good!

2019-07-10 00:29 UTC, merged